# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GITHUB\agendamento\telas\LOGIN.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 496)
        MainWindow.setStyleSheet("background-color: rgb(177, 177, 177);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.adm = QtWidgets.QLabel(self.centralwidget)
        self.adm.setGeometry(QtCore.QRect(390, 50, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.adm.setFont(font)
        self.adm.setAlignment(QtCore.Qt.AlignCenter)
        self.adm.setObjectName("adm")
        self.login = QtWidgets.QLabel(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(350, 140, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setObjectName("login")
        self.senha = QtWidgets.QLabel(self.centralwidget)
        self.senha.setGeometry(QtCore.QRect(330, 200, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.senha.setFont(font)
        self.senha.setObjectName("senha")
        self.c_login = QtWidgets.QLineEdit(self.centralwidget)
        self.c_login.setGeometry(QtCore.QRect(440, 150, 181, 31))
        self.c_login.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.c_login.setObjectName("c_login")
        self.c_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.c_senha.setGeometry(QtCore.QRect(440, 210, 181, 31))
        self.c_senha.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.c_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.c_senha.setObjectName("c_senha")
        self.entrar = QtWidgets.QPushButton(self.centralwidget)
        self.entrar.setGeometry(QtCore.QRect(460, 330, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.entrar.setFont(font)
        self.entrar.setObjectName("entrar")
        self.aviso = QtWidgets.QLabel(self.centralwidget)
        self.aviso.setGeometry(QtCore.QRect(250, 260, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.aviso.setFont(font)
        self.aviso.setText("")
        self.aviso.setAlignment(QtCore.Qt.AlignCenter)
        self.aviso.setObjectName("aviso")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1014, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.adm.setText(_translate("MainWindow", "Administrativo"))
        self.login.setText(_translate("MainWindow", "Login:"))
        self.senha.setText(_translate("MainWindow", "Senha:"))
        self.entrar.setText(_translate("MainWindow", "Entrar"))
