# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GITHUB\agendamento\telas\tela1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 588)
        MainWindow.setStyleSheet("background-color: rgb(177, 177, 177);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-100, -10, 1571, 101))
        self.label.setStyleSheet("background-color: rgb(255, 220, 114);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.consultas = QtWidgets.QPushButton(self.centralwidget)
        self.consultas.setGeometry(QtCore.QRect(30, 20, 191, 41))
        self.consultas.setObjectName("consultas")
        self.pacientes = QtWidgets.QPushButton(self.centralwidget)
        self.pacientes.setGeometry(QtCore.QRect(260, 20, 191, 41))
        self.pacientes.setObjectName("pacientes")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.consultas.setText(_translate("MainWindow", "Consultas"))
        self.pacientes.setText(_translate("MainWindow", "Pacientes"))
